simpak/controllers/UserController.php
<?php

namespace simpak\controllers;

use simpak\models\UserSearch;
use common\models\User;
use Yii;
use yii\filters\VerbFilter;
use yii\helpers\Html;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\Response;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'bulk-delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }


    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $request = Yii::$app->request;
        $model = $this->findModel($id);

        if ($request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return [
                'title' => "User #" . $model->USERNAME,
                'content' => $this->renderAjax('view', [
                    'model' => $model,
                ]),
                'footer' => Html::button('Tutup', ['class' => 'btn btn-default', 'data-dismiss' => "modal"]),
            ];
        } else {
            return $this->render('view', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Creates a new User model.
     * For ajax request will return json object
     * and for non-ajax request if creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $request = Yii::$app->request;
        $model = new User(['scenario' => 'register']);

        if ($request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            if ($request->isGet) {
                return [
                    'title' => "Tambah User",
                    'content' => $this->renderAjax('create', [
                        'model' => $model,
                    ]),
                    'footer' => Html::button(
                            'Tutup',
                            ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]
                        ) . Html::button(
                            'Simpan',
                            ['class' => 'btn btn-primary', 'type' => "submit"]
                        ),
                ];
            } else {
                if ($model->load($request->post())) {
                    $model->generateAuthKey();
                    $model->setPassword($model->password);
                    if ($model->save()){
                        Yii::$app->authManager->assign(Yii::$app->authManager->getRole($model->role), $model->ID);
                        return [
                            'title' => "Tambah User",
                            'content' => $this->renderAjax('create', [
                                'model' => $model,
                            ]),
                            'footer' => Html::button(
                                    'Tutup',
                                    ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]
                                ) . Html::button(
                                    'Simpan',
                                    ['class' => 'btn btn-primary', 'type' => "submit"]
                                ),
                        ];
                    } else {
                        return [
                            'forceReload' => '#crud-datatable-pjax',
                            'title' => "Tambah User",
                            'content' => '<span class="text-success">Data Berhasil Ditambahkan...</span>',
                            'footer' => Html::button('Tutup', ['class' => 'btn btn-default', 'data-dismiss' => "modal"]),
                        ];
                    }
                } else {
                    return [
                        'title' => "Tambah User",
                        'content' => $this->renderAjax('create', [
                            'model' => $model,
                        ]),
                        'footer' => Html::button(
                                'Tutup',
                                ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]
                            ) . Html::button(
                                'Simpan',
                                ['class' => 'btn btn-primary', 'type' => "submit"]
                            ),
                    ];
                }
            }
        } else {
            if ($model->load($request->post())) {
                $model->generateAuthKey();
                $model->setPassword($model->password);
                if ($model->save()) {
                    Yii::$app->authManager->assign(Yii::$app->authManager->getRole($model->role), $model->ID);
                    return $this->redirect(['view', 'id' => $model->ID]);
                } else {
                    return $this->render('create', [
                        'model' => $model,
                    ]);
                }
            } else {
                return $this->render('create', [
                    'model' => $model,
                ]);
            }
        }
    }

    /**
     * Updates an existing User model.
     * For ajax request will return json object
     * and for non-ajax request if update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $request = Yii::$app->request;
        $model = $this->findModel($id);

        if ($request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            if ($request->isGet) {
                return [
                    'title' => "Update User #" . $model->USERNAME,
                    'content' => $this->renderAjax('update', [
                        'model' => $model,
                    ]),
                    'footer' => Html::button(
                            'Tutup',
                            ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]
                        ) . Html::button(
                            'Simpan',
                            ['class' => 'btn btn-primary', 'type' => "submit"]
                        ),
                ];
            } else {
                if ($model->load($request->post()) && $model->save()) {
                    Yii::$app->authManager->revokeAll($id);
                    Yii::$app->authManager->assign(Yii::$app->authManager->getRole($model->role), $model->ID);
                    return [
                        'forceReload' => '#crud-datatable-pjax',
                        'title' => "Tambah User",
                        'content' => '<span class="text-success">Data Berhasil Ditambahkan...</span>',
                        'footer' => Html::button('Tutup', ['class' => 'btn btn-default', 'data-dismiss' => "modal"]),
                    ];
                } else {
                    return [
                        'title' => "Update User #" . $model->USERNAME,
                        'content' => $this->renderAjax('update', [
                            'model' => $model,
                        ]),
                        'footer' => Html::button(
                                'Tutup',
                                ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]
                            ) . Html::button(
                                'Simpan',
                                ['class' => 'btn btn-primary', 'type' => "submit"]
                            ),
                    ];
                }
            }
        } else {
            if ($model->load($request->post()) && $model->save()) {
                Yii::$app->authManager->revokeAll($id);
                Yii::$app->authManager->assign(Yii::$app->authManager->getRole($model->role), $model->ID);
                return $this->redirect(['view', 'id' => $model->ID]);
            } else {
                return $this->render('update', [
                    'model' => $model,
                ]);
            }
        }
    }

    /**
     * Delete an existing User model.
     * For ajax request will return json object
     * and for non-ajax request if deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $request = Yii::$app->request;
        $this->findModel($id)->delete();

        if ($request->isAjax) {

            Yii::$app->response->format = Response::FORMAT_JSON;
            return ['forceClose' => true, 'forceReload' => '#crud-datatable-pjax'];
        } else {
            return $this->redirect(['index']);
        }
    }

    /**
     * Update the user data for the user who has logged in.
     *
     * @return string|\yii\web\Response
     * @throws \yii\web\NotFoundHttpException
     */
    public function actionProfile()
    {
        $model = $this->findModel(Yii::$app->user->id);
        if ($model->load(Yii::$app->request->post())) {
            if ($model->save()) {
                return $this->redirect(['view', 'id' => $model->ID]);
            }
        }

        return $this->render('profile', [
            'model' => $model,
        ]);
    }

    /**

simpak/views/layouts/blank.php
<?php

use simpak\assets\AppAsset;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $content string */

// Favicon
$this->registerLinkTag([
    'rel' => 'icon',
    'href' => Yii::getAlias('@web/favicon.ico'),
    'type' => 'image/x-icon',
]);

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="noindex, nofollow">
    <?= Html::csrfMetaTags() ?>
    <title>IAI-SOLO &raquo; <?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="<?= ArrayHelper::getValue(Yii::$app->params, 'bodyClass', 'skin-red sidebar-mini') ?>">
<?php $this->beginBody() ?>
<?= $content; ?>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

simpak/views/layouts/footer.php
<?php
/* @var $this yii\web\View */
?>
<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <b>Versi</b> 0.1.0
    </div>
    <strong>
        Copyright &copy; <?= date('Y'); ?> <a href="http://www.puskom.uns.ac.id">NEXPLAN</a>.
    </strong> All rights reserved.
</footer>

simpak/views/layouts/header.php
<?php

use cebe\gravatar\Gravatar;
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $identity common\models\User */
/* @var $user yii\web\User */

$user = Yii::$app->user;
$identity = $user->identity;
?>
<header class="main-header">
    <?= Html::a(
        Html::tag('span', Html::img(Yii::getAlias('@web/img/iai-logo-mini.jpg')), ['class' => 'logo-mini']) .
        Html::tag('span', 'IAI-<b>SOLO</b>', ['class' => 'logo-lg']), ['/site/index'], ['class' => 'logo']
    ); ?>

    <nav class="navbar navbar-static-top" role="navigation">
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                
                <?php if (!$user->isGuest): ?>
                    <li class="dropdown user user-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <?= Gravatar::widget([
                                'email' => $identity->EMAIL,
                                'options' => [
                                    'alt' => $identity->USERNAME,
                                    'class' => 'user-image',
                                ],
                                'size' => 25,
                            ]); ?>
                            <span class="hidden-xs"><?= $identity->FULL_NAME; ?></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="user-header">
                                <?= Gravatar::widget([
                                    'email' => $identity->EMAIL,
                                    'options' => [
                                        'alt' => $identity->USERNAME,
                                        'class' => 'img-circle',
                                    ],
                                    'size' => 84,
                                ]); ?>

                                <p><?= $identity->FULL_NAME; ?></p>
                            </li>
                            <li class="user-footer">
                                <div class="pull-right">
                                    <?= Html::a(
                                        'Keluar',
                                        ['/site/logout'],
                                        ['class' => 'btn btn-default btn-flat', 'data-method' => 'post']
                                    ); ?>

                                </div>
                            </li>
                        </ul>
                    </li>
                <?php else: ?>
                    <li>
                        <a href="<?= Url::to(['/site/login']); ?>">
                            <i class="fa fa-sign-in"></i> <span>Login</span>
                        </a>
                    </li>
                <?php endif; ?>

            </ul>
        </div>
    </nav>
</header>

simpak/views/layouts/main.php
<?php

use themes\adminlte\widgets\Alert;
use yii\helpers\Html;
use yii\widgets\Breadcrumbs;

/* @var $this yii\web\View */
/* @var $content string */

$this->beginContent('@app/views/layouts/blank.php');
?>
<div class="wrapper">
    <?= $this->render('header'); ?>
    <?= $this->render('sidebar'); ?>
    <div class="content-wrapper">
        <section class="content-header">
            <h1><?= $this->title; ?></h1>
            <?= Breadcrumbs::widget([
                'homeLink' => [
                    'label' => Html::a(
                        '<i class="fa fa-dashboard"></i>' . Yii::t('app', 'Beranda'),
                        Yii::$app->homeUrl
                    ),
                ],
                'encodeLabels' => false,
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ]) ?>
        </section>
        <section class="content clearfix">
            <?= Alert::widget() ?>
            <?= $content; ?>
        </section>
    </div>
    <?= $this->render('footer'); ?>
</div>
<?php $this->endContent(); ?>

simpak/views/layouts/rbac.php
<?php

use themes\adminlte\widgets\Alert;
use yii\helpers\Html;
use yii\widgets\Breadcrumbs;

/* @var $this yii\web\View */
/* @var $content string */

$this->beginContent('@app/views/layouts/blank.php');
$this->registerCss('.box-body h1{display:none}');
?>
<div class="wrapper">
    <?= $this->render('header'); ?>
    <?= $this->render('sidebar'); ?>
    <div class="content-wrapper">
        <section class="content-header">
            <h1><?= $this->title; ?></h1>
            <?= Breadcrumbs::widget([
                'homeLink' => [
                    'label' => Html::a(
                        '<i class="fa fa-dashboard"></i>' . Yii::t('app', 'Beranda'),
                        Yii::$app->homeUrl
                    ),
                ],
                'encodeLabels' => false,
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ]) ?>
        </section>
        <section class="content clearfix">
            <?= Alert::widget() ?>
            <div class="box box-danger">
                <div class="box-body">
                    <?= $content; ?>
                </div>
            </div>
        </section>
    </div>
    <?= $this->render('footer'); ?>
</div>
<?php $this->endContent(); ?>

simpak/views/layouts/sidebar.php
<?php

use cebe\gravatar\Gravatar;
use themes\adminlte\widgets\Menu;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $identity \common\models\User */

$identity = Yii::$app->user->identity;
?>
<aside class="main-sidebar">
    <section class="sidebar">

        <?php if (!Yii::$app->user->isGuest) : ?>
            <div class="user-panel">
                <div class="pull-left image">
                    <?=
                    Gravatar::widget([
                        'email' => $identity->EMAIL,
                        'options' => [
                            'alt' => $identity->USERNAME,
                            'class' => 'img-circle',
                        ],
                        'size' => 45,
                    ])
                    ?>
                </div>
                <div class="pull-left info">
                    <p><?= $identity->FULL_NAME; ?></p>
                    <?=
                    Html::a(
                        '<i class="circle text-success"></i>'
                            . 'Online',
                        ['/user/profile']
                    )
                    ?>
                </div>
            </div>
        <?php endif ?>

        <?php
        $adminMenu[] = [
            'label' => Yii::t('app', 'MENU UTAMA'),
            'options' => ['class' => 'header'],
            'template' => '{label}',
        ];

        $adminMenu[] = [
            'icon' => 'home',
            'label' => Yii::t('app', 'Home'),
            'url' => ['/site/index'],
        ];

        $adminMenu[] = [
            'label' => 'Anggota',
            'icon' => 'address-book',
            'items' => [
                [
                    'icon' => 'circle-o',
                    'label' => Yii::t('app', 'Data Utama'),
                    'url' => ['/anggota/site/index'],
                    'visible' => Yii::$app->user->can('perm_anggota'),
                ],
                [
                    'icon' => 'circle-o',
                    'label' => Yii::t('app', 'Pendidikan'),
                    'url' => ['/anggota/pendidikan/index'],
                    'visible' => Yii::$app->user->can('perm_anggota'),
                ],
                [
                    'icon' => 'circle-o',
                    'label' => Yii::t('app', 'Pekerjaan'),
                    'url' => ['/anggota/pekerjaan/index'],
                    'visible' => Yii::$app->user->can('perm_anggota'),
                ],
                [
                    'icon' => 'circle-o',
                    'label' => Yii::t('app', 'Iuran'),
                    'url' => ['/anggota/iuran/index'],
                    'visible' => Yii::$app->user->can('perm_anggota'),
                ],
                [
                    'icon' => 'circle-o',
                    'label' => Yii::t('app', 'Sertifikat'),
                    'url' => ['/anggota/sertif/index'],
                    'visible' => Yii::$app->user->can('perm_anggota'),
                ],
            ],
            'visible' => Yii::$app->user->can('perm_anggota'),
        ];

        $adminMenu[] = [
            'label' => 'Sekretaris',
            'icon' => 'address-book',
            'items' => [
                [
                    'icon' => 'circle-o',
                    'label' => Yii::t('app', 'Daftar Anggota'),
                    'url' => ['/sekretaris/site/index'],
                    'visible' => Yii::$app->user->can('perm_sekretaris'),
                ],
            ],
            'visible' => Yii::$app->user->can('perm_sekretaris'),
        ];

        $adminMenu[] = [
            'label' => 'Bendahara',
            'icon' => 'calculator',
            'items' => [
                [
                    'icon' => 'circle-o',
                    'label' => Yii::t('app', 'Iuran Anggota'),
                    'url' => ['/bendahara/iuran/index'],
                    'visible' => Yii::$app->user->can('perm_bendahara'),
                ],
                [
                    'icon' => 'circle-o',
                    'label' => Yii::t('app', 'Referensi Iuran'),
                    'url' => ['/bendahara/ref-iuran/index'],
                    'visible' => Yii::$app->user->can('perm_bendahara'),
                ],
            ],
            'visible' => Yii::$app->user->can('perm_bendahara'),
        ];

        $adminMenu[] = [
            'label' => 'Agenda',
            'icon' => 'calculator',
            'items' => [
                [
                    'icon' => 'circle-o',
                    'label' => Yii::t('app', 'Manajemen Agenda'),
                    'url' => ['/agenda/site/index'],
                    'visible' => Yii::$app->user->can('perm_agenda_manajemen'),
                ],
                [
                    'icon' => 'circle-o',
                    'label' => Yii::t('app', 'Riwayat Agenda'),
                    'url' => ['/agenda/riwayat/index'],
                    'visible' => Yii::$app->user->can('perm_agenda_riwayat'),
                ],
                [
                    'icon' => 'circle-o',
                    'label' => Yii::t('app', 'Riwayat Pembayaran Agenda'),
                    'url' => ['/agenda/pembayaran/index'],
                    'visible' => Yii::$app->user->can('perm_agenda_pembayaran'),
                ],
            ],
            'visible' => Yii::$app->user->can('perm_agenda_riwayat'),
        ];

        $adminMenu[] = [
            'label' => 'Administrator System',
            'icon' => 'users',
            'items' => [
                [
                    'label' => Yii::t('app', 'Pengaturan User'),
                    'icon' => 'users',
                    'items' => [
                        [
                            'icon' => 'circle-o',
                            'label' => Yii::t('app', 'Semua User'),
                            'url' => ['/user/index'],
                            'visible' => Yii::$app->user->can('role_superuser'),
                        ],
                        [
                            'icon' => 'circle-o',
                            'label' => Yii::t('app', 'Tambah User'),
                            'url' => ['/user/create'],
                            'visible' => Yii::$app->user->can('role_superuser'),
                        ],
                        [
                            'icon' => 'circle-o',
                            'label' => Yii::t('app', 'Profil Saya'),
                            'url' => ['/user/profile'],
                            'visible' => Yii::$app->user->can('role_superuser'),
                        ],
                        [
                            'icon' => 'circle-o',
                            'label' => Yii::t('app', 'Ubah Kata Sandi'),
                            'url' => ['/user/reset-password'],
                            'visible' => Yii::$app->user->can('role_superuser'),
                        ],
                        [
                            'icon' => 'circle-o',
                            'label' => Yii::t('app', 'RBAC'),
                            'url' => ['/rbac/assignment/index'],
                            'visible' => Yii::$app->user->can('role_superuser'),
                        ],
                    ],
                ],
                [
                    'label' => 'Referensi',
                    'icon' => 'list',
                    'url' => ['/referensi/default/index'],
                    'visible' => Yii::$app->user->can('role_superuser'),
                ],
                [
                    'label' => 'Setting',
                    'icon' => 'list',
                    'url' => ['/referensi/setting/index'],
                    'visible' => Yii::$app->user->can('role_superuser'),
                ],
            ],
            'visible' => Yii::$app->user->can('role_superuser'),
        ];

        $adminMenu[] = [
            'icon' => 'sign-in',
            'label' => Yii::t('app', 'Login'),
            'url' => ['/site/login'],
            'visible' => Yii::$app->user->isGuest,
        ];

        $adminMenu[] = [
            'icon' => 'sign-out',
            'label' => Yii::t('app', 'Logout'),
            'url' => ['/site/logout'],
            'linkOptions' => ['data-method' => 'post'],
            'visible' => !Yii::$app->user->isGuest,
        ];

        if (isset(Yii::$app->params['adminMenu']) && is_array(Yii::$app->params['adminMenu'])) {
            $adminMenu = ArrayHelper::merge($adminMenu, Yii::$app->params['adminMenu']);
        }

        echo Menu::widget([
            'items' => $adminMenu,
        ]);
        ?>
    </section>
</aside>